[versions]
agp = "8.3.0"
kotlin = "1.9.0"
koinBom = "3.6.0-wasm-alpha2"
room = "2.6.1"
ksp = "1.9.21-1.0.15"
serializationPlugin = "1.8.10"
navigationCompose = "2.7.7"

[libraries]
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin = { group = "io.insert-koin", name = "koin-core" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }


[bundles]
room = ["room-ktx", "room-paging", "room-runtime"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
