[versions]
agp = "8.3.0"
kotlin = "1.9.0"
koinBom = "3.6.0-wasm-alpha2"
ksp = "1.9.21-1.0.15"
lifecycleRuntimeCompose = "2.6.0-alpha03"
navigationCompose = "2.7.7"
paging = "3.1.1"
pagingCompose = "1.0.0-alpha17"
room = "2.4.3"
serializationPlugin = "1.8.10"

[libraries]
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }


[bundles]
room = ["room-ktx", "room-paging", "room-runtime"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin" }
